# Generated by Django 4.0.3 on 2022-04-01 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mc_site', '0003_cart_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mc_site.address'),
            preserve_default=False,
        ),
    ]
