# Generated by Django 4.0.3 on 2022-04-01 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mc_site', '0004_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
